-- Create extension "vector"
CREATE EXTENSION "vector" WITH SCHEMA "public";
  -- Create "chunks" table
CREATE TABLE "public"."chunks" (
   "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "path" character varying NOT NULL,
   "nchunk" bigint NOT NULL,
   "data" text NOT NULL,
   PRIMARY KEY ("id")
);
-- Create "embeddings" table
CREATE TABLE "public"."embeddings" (
   "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
   "embedding" public.vector(768) NOT NULL,
   "chunk_id" bigint NOT NULL,
   PRIMARY KEY ("id"),
   CONSTRAINT "embeddings_chunks_embedding" FOREIGN KEY ("chunk_id") REFERENCES "public"."chunks" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "embedding_embedding" to table: "embeddings"
CREATE INDEX "embedding_embedding" ON "public"."embeddings" USING hnsw ("embedding" vector_l2_ops);
-- Create index "embeddings_chunk_id_key" to table: "embeddings"
CREATE UNIQUE INDEX "embeddings_chunk_id_key" ON "public"."embeddings" ("chunk_id");